### ISSUE TITLE
Example model fails to work

### ISSUE THREAD

**Issue by alexellis** [oauthjs/node-oauth2-server#351]
Example model at https://github.com/oauthjs/node-oauth2-server/wiki/Model-specification fails to work with Node 6.x. Please double-check.

```
oauth alex$ node index.js 
/Users/alex/dev/alexa-secretkeeper/oauth/node_modules/oauth2-server/lib/server.js:24
  this.options = options;
               ^

TypeError: Cannot set property 'options' of undefined
    at OAuth2Server (/Users/alex/dev/alexa-secretkeeper/oauth/node_modules/oauth2-server/lib/server.js:24:16)
    at Object.<anonymous> (/Users/alex/dev/alexa-secretkeeper/oauth/index.js:31:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Complete example:

```
"use strict"

var model = {
  // We support generators.
  getAccessToken: function () {
      
    return 'works!'
  },

  // Or, async/await (using _babel_).
  getAuthorizationCode: function() {
    return 'works';
  },

  // Or, calling a node-style callback.
  getClient: function(done) {

    done(null, 'works!');
  },

  // Or, returning a promise.
  getUser: function() {
    return new Promise('works!');
  },
};

let express = require("express")
var app = express();
var options = { model: model };
var oauth2server = require('oauth2-server')
let oauth= oauth2server(options);

app.use(oauth.authenticate());

app.get('/', function (req, res) {
  res.send('Hello World');
})

app.listen(3000);
```

**Comment by maxtruxa** [comment]
Same as the README, the Wiki page is out-of-date.
Calling the `OAuth2Server` constructor correctly (with `new`) fixes the problem:

```
let oauth = new oauth2server(options);
```

**Comment by maxtruxa** [comment]
See #341.
