### ISSUE TITLE
Errors happening for typical events in v2.4.1 when used with express

### ISSUE THREAD

**Issue by subatomicglue** [oauthjs/node-oauth2-server#411]
```
OAuth2Error: The access token provided is invalid.
    at OAuth2Error (.../node_modules/oauth2-server/lib/error.js:30:12)
    at .../node_modules/oauth2-server/lib/authorise.js:114:19
    at Object.model.getAccessToken (.../src/oauth2-mysql-model.js:17:32)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

Configuration:
```
app.oauth = oauthserver({
    model: require('./oauth2-mysql-model'),
    //model: require('./oauth2-memory-model'), // do NOT use in PRODUCTION
    grants: ['password', 'refresh_token'],
    debug: true,
    accessTokenLifetime: null, // never expire
    refreshTokenLifetime: null, // never expire
    authCodeLifetime: 1200,
    clientIdRegex: /^[a-z0-9-_]{3,40}$/i,
    allowExtendedTokenAttributes: true, // return additional properties from model.saveToken() which will be included in the token response:
    passthroughErrors: false
  });
```

my `model.getAccessToken` is
```
model.getAccessToken = async function( bearerToken, callback ) {
  try {
    let result = await db.query( db.WRITE, 'SELECT access_token, client_id, expires, user_id FROM oauth_access_tokens WHERE access_token = ?', [bearerToken] );

    // this one just gives "server error"...  which is not informative
    //if (!result.length) return callback( "access token not found in the db (oauth_access_tokens)", null );

    // this is the line in the stacktrace above:
    //          at Object.model.getAccessToken ( .../src/oauth2-mysql-model.js:17:32)
    // this one at least gives the message "OAuth2Error: The access token provided is invalid", but outputs stacktrace spew onto the command line for a "normal event"  (someone giving a wrong token shouldn't be an exception, it happens!)...
    if (!result.length) return callback( undefined, null );

    // This object will be exposed in req.oauth.token
    // The userId field will be exposed in req.user.id (req.user = { id: "..." }) however if
    // an explicit user object is included (token.user, must include id) it will be exposed
    // in req.user instead
    var token = result[0];
    let user = await users.getUserFromID( token.user_id );
    let retval = {
      accessToken: token.access_token,
      clientId: token.client_id,
      // puts the user data into req.user
      user: {
        id: user.id,
        email: user.emails_obj[0].email
      },
      //userId: token.user_id, // puts the user data into req.user.id
      expires: token.expires
    };
    callback(null, retval);
  } catch (err) {
    return callback( err );
  }
};
```

Is there a way to suppress?

**Comment by subatomicglue** [comment]
Similarly, I get this when logging in with username/password.  Which I dont expect a failed log in to be an exceptional event, and dont need the log spam.

```
OAuth2Error: false
    at OAuth2Error (.../node_modules/oauth2-server/lib/error.js:30:12)
    at .../node_modules/oauth2-server/lib/grant.js:226:26
    at Object.model.getUser (.../src/oauth2-mysql-model.js:126:14)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by subatomicglue** [comment]
Additionally, when I make an http request with invalid token, I get this:

Actually returned in the response... 
```
500 (Internal Server Error)
OAuth2Error: The access token provided is invalid.<br> &nbsp; &nbsp;at OAuth2Error (.../src/Platform/back/node_modules/oauth2-server/lib/error.js:30:12)<br> &nbsp; &nbsp;at .../src/Platform/back/node_modules/oauth2-server/lib/authorise.js:114:19<br> &nbsp; &nbsp;at Object.model.getAccessToken (.../src/Platform/back/src/oauth2-mysql-model.js:18:32)<br> &nbsp; &nbsp;at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

How do I take control of the server, and rid these error messages - customize them to 401s, or smarter responses than "server error".   Hard to take action when the response is so obtuse.

**Comment by subatomicglue** [comment]
Summary of responses:

**Get Oauth Token from /oauth, bad username or password:**
```
{
  "code": 503,
  "error": "server_error",
  "error_description": "server_error"
}
```
console:
```
OAuth2Error: false
    at OAuth2Error (.../node_modules/oauth2-server/lib/error.js:30:12)
    at .../node_modules/oauth2-server/lib/grant.js:226:26
    at Object.model.getUser (.../src/oauth2-mysql-model.js:129:16)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Get oauth token from /oauth,  missing auth header**
```
{
  "code": 400,
  "error": "invalid_client",
  "error_description": "Invalid or missing client_id parameter"
}
```
console:
```
    at next (.../node_modules/express/lib/router/index.js:271:10)
    at allowCrossDomain (.../src/app.js:168:5)
    at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (.../node_modules/express/lib/router/index.js:312:13)
    at .../node_modules/express/lib/router/index.js:280:7
    at Function.process_params (.../node_modules/express/lib/router/index.js:330:12)
    at next (.../node_modules/express/lib/router/index.js:271:10)
    at methodOverride (.../node_modules/method-override/index.js:79:5)
    at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)
```

**Get oauth token from /oauth,  invalid Basic:**
```
{
  "code": 400,
  "error": "invalid_client",
  "error_description": "Client credentials are invalid"
}
```
console:
```
OAuth2Error: Client credentials are invalid
    at OAuth2Error (.../node_modules/oauth2-server/lib/error.js:30:12)
    at .../node_modules/oauth2-server/lib/grant.js:141:19
    at Object.model.getClient (.../src/oauth2-mysql-model.js:47:32)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**`/secret` endpoint call with 'authorise()' middleware, and missing Auth header:**
```
{
  "code": 400,
  "error": "invalid_request",
  "error_description": "The access token was not found"
}
```
console:
```
OAuth2Error: The access token was not found
    at OAuth2Error (.../node_modules/oauth2-server/lib/error.js:30:12)
    at Authorise.getBearerToken (.../node_modules/oauth2-server/lib/authorise.js:70:17)
    at run (.../node_modules/oauth2-server/lib/runner.js:15:14)
    at runner (.../node_modules/oauth2-server/lib/runner.js:19:5)
    at new Authorise (.../node_modules/oauth2-server/lib/authorise.js:45:3)
    at .../node_modules/oauth2-server/lib/oauth2server.js:70:12
    at module.exports.authorize (.../src/auth.js:71:46)
    at Layer.handle [as handle_request] (.../node_modules/express/lib/router/layer.js:95:5)
    at next (.../node_modules/express/lib/router/route.js:131:13)
```

**`/secret` endpoint call with 'authorise()' middleware, and invalid Bearer token:**
```
{
  "code": 401,
  "error": "invalid_token",
  "error_description": "The access token provided is invalid."
}
```
console:
```
OAuth2Error: The access token provided is invalid.
    at OAuth2Error (.../node_modules/oauth2-server/lib/error.js:30:12)
    at .../node_modules/oauth2-server/lib/authorise.js:114:19
    at Object.model.getAccessToken (.../src/oauth2-mysql-model.js:18:32)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by subatomicglue** [comment]
How do I take control of this, and rid the console spam - customize the 503 and 400's to all be 401s,  and give smarter reading responses than "server error".
