### ISSUE TITLE
invalid input syntax for uuid

### ISSUE THREAD

**Issue by wellington-cunha** [oauthjs/node-oauth2-server#412]
Hello Everybody. 

I have installed and perform all working tests for node-oauth2-server and I was step by step plug it into Postgres that seems to work properly till I try to post to 
"http://localhost:3000/oauth/token"
the follow informations 
"grant_type=password&client_id=opp&client_secret=OPP-SECRET123&username=wellington&password=123456"

I got the follow errors
"{
"code": 503,
"error": "server_error",
"error_description": "server_error"
}"

on my ARC.

on my server console the logs appears is 

"error: invalid input syntax for uuid: "{"id":"afd0b036-625a-3aa8-b639-9dc8c8fff0ff"}"
    at Connection.parseE (/Users/wellington/node-oauth2-server/node-oauth2-server-example/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/wellington/node-oauth2-server/node-oauth2-server-example/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/wellington/node-oauth2-server/node-oauth2-server-example/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:563:20)"

Thank everybody

**Comment by cirick** [comment]
This looks like a Postgres error for it's UUID formatting on your database entry. You might want to take a look at the Postgres docs.

**Comment by wellington-cunha** [comment]
Thank for you reply. I already solved the problem.
The problem is being generate cause in the file
"oauth2-server/examples/postgresql/model.js" 
in line 124
"callback(err, result.rowCount ? result.rows[0] : false);"

after run the follow query "'SELECT id FROM users WHERE username = $1 AND password = $2', [username,   password]"

instead get "{"id":"afd0b036-625a-3aa8-b639-9dc8c8fff0ff"}" the lib expect this
"afd0b036-625a-3aa8-b639-9dc8c8fff0ff" that can be solve changing code 
from 
"callback(err, result.rowCount ? result.rows[0] : false);" 
to
"callback(err, result.rowCount ? result.rows[0]["id"] : false);"

I hope somebody is having this same problem can benefit from this information.
