### ISSUE TITLE
error when install 3x with "npm install oauth2-server@^3.0.0-b1"

### ISSUE THREAD

**Issue by Luomusha** [oauthjs/node-oauth2-server#415]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/nodejs8x/bin/node',
1 verbose cli   '/usr/local/nodejs/bin/npm',
1 verbose cli   'install',
1 verbose cli   'oauth2-server@^3.0.0-b1' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose npm-session 59415ed34a8afd18
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/oauth2-server 2378ms (from cache)
8 silly pacote range manifest for oauth2-server@^3.0.0-b1 fetched in 2410ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule oauth2-server@3.0.0-b4 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/promisify-any 267ms (from cache)
15 silly pacote version manifest for promisify-any@2.0.1 fetched in 270ms
16 silly resolveWithNewModule promisify-any@2.0.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/basic-auth 994ms (from cache)
18 silly pacote version manifest for basic-auth@1.1.0 fetched in 999ms
19 silly resolveWithNewModule basic-auth@1.1.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/bluebird 3506ms (from cache)
21 silly fetchPackageMetaData error for bluebird@3.5.0 Unexpected end of input at 1:117911
21 silly fetchPackageMetaData lify-js":"~2.4.16"},"directories":{},"dist":{"shasum":"14a2e75f054832
21 silly fetchPackageMetaData                                                                      ^
22 verbose stack SyntaxError: Unexpected end of input at 1:117911
22 verbose stack lify-js":"~2.4.16"},"directories":{},"dist":{"shasum":"14a2e75f054832
22 verbose stack                                                                      ^
22 verbose stack     at Object.parseJSON (/usr/local/nodejs8x/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
22 verbose stack     at parse (/usr/local/nodejs8x/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
22 verbose stack     at consumeBody.call.then.buffer (/usr/local/nodejs8x/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
22 verbose stack     at <anonymous>
22 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
23 verbose cwd /home/lossa/WebstormProjects/mykoa
24 verbose Linux 4.9.0-3-amd64
25 verbose argv "/usr/local/nodejs8x/bin/node" "/usr/local/nodejs/bin/npm" "install" "oauth2-server@^3.0.0-b1"
26 verbose node v8.2.1
27 verbose npm  v5.3.0
28 error Unexpected end of input at 1:117911
28 error lify-js":"~2.4.16"},"directories":{},"dist":{"shasum":"14a2e75f054832
28 error                                                                      ^
29 verbose exit [ 1, true ]

**Comment by Luomusha** [comment]
node 8.2.1
npm 5.3.0

**Comment by Luomusha** [comment]
Debian 9

**Comment by Luomusha** [comment]
well ,i'm done with "npm cache clean --force"
