### ISSUE TITLE
TypeError: Cannot set property 'options' of undefined in server.js

### ISSUE THREAD

**Issue by andychoi** [oauthjs/node-oauth2-server#450]
I got error like below.

`<test folder>\node_modules\oauth2-server\lib\server.js:24
  this.options = options;
               ^

TypeError: Cannot set property 'options' of undefined
    at OAuth2Server (<test folder>\node_modules\oauth2-server\lib\server.js:24:16)
    at Object.<anonymous> (C:\Users\<test script>.js:13:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3`

**Comment by maxtruxa** [comment]
You forgot `new`.

```
var oauth = OAuth2Server({...});
```
vs.
```
var oauth = new OAuth2Server({...});
```

**Comment by marcinwasilewski** [comment]
There is an issue with [documentation for the npm package](https://www.npmjs.com/package/node-oauth2-server) where it's missing "new" keyword as well.
