### ISSUE TITLE
TypeError: app.oauth.grant is not a function

### ISSUE THREAD

**Issue by dzarezenko** [oauthjs/node-oauth2-server#480]
I am trying to run this script:
```javascript
var express = require('express'),
        bodyParser = require('body-parser'),
        OAuth2Server = require('oauth2-server');

    var app = express();

    app.use(bodyParser.urlencoded({ extended: true }));

    app.use(bodyParser.json());

    app.use(function (req, res, next) {
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
        res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
        res.setHeader('Access-Control-Allow-Credentials', true);
        // Pass to next layer of middleware
        next();
    });

    app.oauth = new OAuth2Server({
        model: require('./model.js'),
        grants: ['password', 'client_credentials'],
        debug: true
    });

    app.all('/oauth/token', app.oauth.grant());

    app.use(app.oauth.errorHandler());

    app.listen(3000, function () {
        console.log('Listening on port 3000...');
    });
```

and received this error:

```
TypeError: app.oauth.grant is not a function
    at Object.<anonymous> (/usr/myapi/www/api/daemon.js:39:39)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

How can I fix it?

**Comment by tobilg** [comment]
I think you should use https://github.com/oauthjs/express-oauth-server/ and replace the line with

```javascript
app.post('/oauth/token', app.oauth.token());
```

**Comment by frankjrangel** [comment]
In v3 methods were renamed, check the docs [here]( https://oauth2-server.readthedocs.io/en/latest/misc/migrating-v2-to-v3.html). You could use v2 or just use the new methods.
