### ISSUE TITLE
Authorization code is invalid

### ISSUE THREAD

**Issue by ReeSilva** [oauthjs/node-oauth2-server#545]
Hi guys. I'm facing an weird (looks like more of one of the Javascript weird behaviors).

When I call the **token** method, even with strictly equal `code.client.id` and `client.id`, the lib act like it is different and throw an `authorization code is invalid`.

I've edited the lib code to console.log the fields and they are strictly equal. Someone has faced it anytime?

This is the lib code edited to log field values
```javascript
console.log(code.client.id);
console.log(client.id);
console.log(typeof code.client.id);
console.log(typeof client.id);
if (code.client.id === client.id) {
  console.log('I\'M THE SAME');
}
if (code.client.id !== client.id) {
  console.log('OUCH! THERE IS SOMETHING WRONG!');
  throw new InvalidGrantError('Invalid grant: authorization code is invalid');
}
```

And this is the return:
```shell
5c07ca524bf90b198c5968c8
5c07ca524bf90b198c5968c8
object
object
OUCH! THERE IS SOMETHING WRONG!
OUCH!
{ invalid_grant: Invalid grant: authorization code is invalid
    at new InvalidGrantError (/home/renato/Projects/oauth2/node_modules/oauth2-server/lib/errors/invalid-grant-error.js:27:14)
    at /home/renato/Projects/oauth2/node_modules/oauth2-server/lib/grant-types/authorization-code-grant-type.js:114:15
    at tryCatcher (/home/renato/Projects/oauth2/node_modules/oauth2-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/renato/Projects/oauth2/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/renato/Projects/oauth2/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/renato/Projects/oauth2/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/renato/Projects/oauth2/node_modules/oauth2-server/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/renato/Projects/oauth2/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/renato/Projects/oauth2/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/renato/Projects/oauth2/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/renato/Projects/oauth2/node_modules/oauth2-server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
  statusCode: 400,
  status: 400,
  code: 400,
  message: 'Invalid grant: authorization code is invalid',
  name: 'invalid_grant' }
```

**Comment by ReeSilva** [comment]
Nevermind, I figure out that the problem is as the string is an object it was being considered an object and the comparison returns false. If I cast to string in the returns the problem goes away.

Closing.
